### ISSUE TITLE
Error en el procedimiento de generación tablas auxiliares

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/decs-api#10]
$ python manage.py savetree D

```
....
Saved "SP6.990.625.344.855", identifier_id "29416", ths "1" Hierarchical Info
Saved "SP6.990.625.344.537.687", identifier_id "29417", ths "1" Hierarchical Info
Saved "SH1.010.020.030.040.050.060", identifier_id "29418", ths "1" Hierarchical Info
Saved "SP1", identifier_id "29419", ths "1" Hierarchical Info
Saved "SP1.101.750.121.143.366", identifier_id "29420", ths "1" Hierarchical Info
Saved "SP5.312.109.198.455", identifier_id "29421", ths "1" Hierarchical Info
Saved "SH1.030.050.040", identifier_id "29422", ths "1" Hierarchical Info
Saved "SP3.522.233.700", identifier_id "29422", ths "1" Hierarchical Info
Saved "SP4.202.220.433", identifier_id "29422", ths "1" Hierarchical Info
Traceback (most recent call last):
  File "/app/manage.py", line 22, in <module>
    main()
  File "/app/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/app/thesaurus/management/commands/savetree.py", line 95, in handle
    category = FirstLevel.objects.get(treeNumber=tree_id_ancestor, thesaurus=ths)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
thesaurus.models_full.FirstLevel.DoesNotExist: FirstLevel matching query does not exist.

```

**Comment by yaznagv** [comment]
Falta la tabla FirstLevel

Ejecutar: 
makemigrations y luego migrate para crear FirtsLevel 

Luego para llenar todas las tablas auxiliares de una vez ejecutar:

python manage.py saveauxiliardata

**Comment by viniciusandrade** [comment]
Hola @yaznagv le comento que la tabla **thesaurus_firstlevel** ya esta creada y populada (conforme print abajo) y tiene un total de 42 records.

Tambien ya ejecuté el comando **python manage.py saveauxiliardata** y los demas pasos fueron ejecutados sin error y ahora estoy ejecutando solamente el comando  **python manage.py savetree D** pues fue el unico que apresenta falla.

![image](https://user-images.githubusercontent.com/349287/199276120-924f5711-417f-41d5-90a5-6fb273598c8b.png)

**Comment by viniciusandrade** [comment]
@yaznagv con los ultimos ajustes enviados fue posible ejecutar completamente los procedimientos de generación de las tablas auxiliares.

Ahora voy solicitar la validación de los resultados de la nueva API.

Gracias.
